diem/dip

.github/workflows/main.yml
Add GHA for automatic site employment of the lip site
=> Add GitHub Actions for deployment

lips/lip-1.md
Add full text of off-chain protocol
=> Add specification to LIP-1

lips/lip-4.md
Describe standardized format for transaction metadata
=> Transaction metadata specification

src/DocComponents/Author/index.js, src/DocComponents/LIPTable/index.js, src/theme/DocItem/index.js, src/utils.js
This adds a fix similar to the one I did for the LIP metadata table for authors, but this addresses the individual LIP pages
=> Add authors fix to individual lip pages

lips/lip-6.md
I've mostly tried to do some wordsmithing.
There are some "TODO"s embedded in paragraphs [TODO... ] for points that I didn't know how to resolve.
The properties are still drafty until I make more progress in formal
specification and verification.
=> [lip-6] Edits

lips/lip-1.mdx
Adding linkage to reference implementation of off-chain protocol
=> Add link to reference implementation

lips/lip-4.md
This format is currently being used on-chain and is ready for last call
=> Move LIP 4 to last call

lips/lip-1.mdx
LIP 1 is has now gone through the entire LIP process and is final
=> Move LIP 1 to final

lips/lip-1.mdx
=> Fix links on LIP 1

lips/lip-4.md
Updated as per request from Cristina
=> Update LIP 4 for some fixes

lips/lip-1.mdx
I've verified this snippet of code against testnet
=> Update Recipient Signature generation reference code in python

lips/lip-7.md
Lip-7 is a process lip on the lifecycle of technical working groups.
=> Submitting lip-7

lips/lip-6.mdx
Discussed with @dahliamalkhi but forgot to modify the last committed PR to include this change.
=> Move to last call

lips/lip-4.md, lips/lip-5.md
These have been in last call for an extended period of time
=> Set LIPs 4 and 5 to final

static/scripts/new-site-redirects.js
these were written when we thought the new url was going to be dip.diem.com/lip-1 instead of dip.diem.com/dip-1 and I unfortunately forgot to change it when we decided to change course
=> Fix redirects

lips/lip-20.md
This PR is the initial draft for LIP-20. This is meant to provide both definitions for how currencies work on-chain (registration, minting, coin operations, SCS v.s. synthetic currencies, burning), and also some level of intuition at the same time provide some intuition and motivation for each these e.g., `Preburn` exists so that off-chain actions can be performed before burning the coins.
=> Initial draft of LIP-20

dips/dip-6.mdx
=> DIP-6 final edits

README-website.md
Also, testing Netlify preview builds.
=> Fixing README-website

dips/dip-20.md
Updates DIP-20 based on Dahlia's comments and suggestions.
=> Revisions to DIP-20

package.json
**Please do not auto merge this**
=> make diem docusaurus components module updates explicit

package.json
Fixes two nits:
Link on logo
highlighting on right sidebar
=> [dip.diem.com] update shared component repo

static/_redirects
https://app.asana.com/0/1194894027764377/1199543934675643/f
=> add redirects from /lip-* to /dip-*

dips/dip-20.md
Addresses a number of additional comments received on DIP-20
=> Address comments 

dips/dip-2.md
- This PR adds a new permission entry for "UpdateConsensusConfig", which is granted to DiemRoot.
=> Added the permission "UpdateConsensusConfig" for DiemRoot

dips/dip-20.md
Addresses comments from the last call phase. Mostly minor changes.
=> [DIP-20] Address last call phase comments

dips/dip-172.md
=> Update dip-172 (grammar/formatting)

dips/dip-158.md
1. Fix rendering on dip.diem.com
2. Update command names and associated sequence flows
3. Other miscellaneous refactoring.
Still todo: clean up of request and response types. Coming in another PR.
=> DIP 158 fast follow

dips/dip-158.md
Removed all items and updated the relevant descriptions.
=> Include only Charge payment type in DIP-158.

dips/dip-10.md
=> DIP10 command name fix

dips/dip-183.md
Minor changes clarifying this is a wallet-to-wallet protocol
=> w2w update dip-183.md

dips/dip-10.md
Introducing some changes to make this a wallet-2-wallet protocol rather than user-to-user (and a few minor cleanups).
=> w2w update to dip-10.md

dips/dip-182.md
Added example for use cases for domain resolution: p2p and p2m
=> DIP182 Add example and move to last call
