diem/dip

.github/workflows/main.yml

Will change this to `yarn deploy --skip-build` wehen we updrade Docusaurus to at least 0.56

Build and then use action to deploy

---

lips/lip-1.md

Be able to specify that we are in manual review state. Then allow manual review state to specify that we have a soft match and other side can provide free-form KYC data.
This also results in changing the KYC data object status field to no longer be a pure enum but instead have the ability to describe why we aborted. This is also probably useful for other cases where we abort

Update for travel rule soft-match/manual review

---

lips/lip-1.mdx
lips/lip-4.md

- Updated the LIPs 1 & 4 with the Metadata struct name changes
- LCS serialization takes a type argument in every client SDK
- Added a concrete pylibra-based example for the generation & signature of dual attestation payload. (let me know if we only want pseudo code for consistency)
Signed-off-by: Nassim Eddequiouaq <nass@fb.com>

Update LIPs with transaction metadata and Travel Rule info

---

lips/lip-8.md

LIP 8 is an extension of LIP 1.  This extension adds merchant functionality to the Off-Chain APIs.  Initially this includes pull payments and auth/capture

Create LIP 8

---

lips/lip-5.md

Update LIP 5 to mention that subaddresses should be single-use and not use private information to generate

Update LIP 5 for subaddresses

---

lips/lip-2.md

- This PR adds the access control policy which already has been implemented in the Libra Framework, which goes:
- Only the TreasuryCompliance role can enable/disable minting the currency 
(technically, by updating the `can_have` field of the `CurrencyInfo` struct in `Libra::update_minting_ability`)

Added the permission entry "{Enable,Disable}Minting(**type**)"

---

lips/lip-6.mdx

Rename:
* Libra -> Diem,
* LN -> DN,
* LA -> DA,
* LPN -> DPN,
* LIP -> DIP.
Problems:
* The links still point to libra to keep them valid.
* The names of the following resources are incorrect now (do not match the codebase): DiemSystem, DiemConfig.

Rename Libra -> Diem

---

src/css/custom.css

The intended behavior of the site is that when the main content is scrolled, the right sidebar should stay in view. Right now it does not

ensure right sidebar stays in view on scroll

---

dips/dip-5.md

1. update hrps 
2. explicitly disallow mixed-cases for diem intent identifier. This has been causing confusions.

[dip5] update hrps and explicitly disallow mixed-cases

---

dips/dip-20.md

The documentation links were outdated since stdlib docs got moved into https://github.com/diem/diem/blob/master/language/diem-framework/modules/doc/

Use the correct links for register*_currency docs

---

dips/dip-1.mdx

* Fix minor typos
* Fix broken URLs
* Use oxford comma to reduce ambiguity
* Standardize use of period in cells
* Replace LCS with BCS
* Fix capitalization of Blockchain and Off-Chain
* Replace "shoulds" with "musts" when applicable to reduce ambiguity

Minor Cosmetic Fixes in DIP-1

---

dips/dip-10.md

Addressing comments in https://github.com/diem/dip/issues/156. Main changes are:
- Added error codes
- Added error object to response
- Reworded PII related discussion
- Remove CSV file 
- Diem ID -> DiemID

DIP-10 Updates

---

dips/dip-14.md
dips/dip-169.md

This PR adds draft for DIP 169: muli-agent transactions.
Issue for discussion is here: #169

Add draft for DIP 169: Multi-agent Transactions

---

dips/dip-172.md

Write up of the Customer VASP registration step, including on-chain structs and events.

Initial draft of Dip 172: P2M On-Chain Registration

---

dips/dip-158.md

- Removed ReadyForSettlement command
- Added expectation for the Merchant VASP to find transaction on the blockchain
- Added abort codes for the AbortPayment command
- Added abort sequences (Missing Recipient Signature, Could Not Put Transaction On-Chain)
- Added appendix about including the reference ID in the transaction metadata (including reference to DIP-10)
- Removed sequence diagram temporarily (until we upload the final image to github and embed from there)

Dip 158 remove ready for settlement

---

dips/dip-10.md

Refactoring DiemID DIP into three DIPS: Diem ID (DIP-10), On-chain domain resolution (https://github.com/diem/dip/pull/187), and Reference ID exchange (https://github.com/diem/dip/pull/186).

DiemID Refactor

---

dips/dip-169.md

This PR removes references to designated dealers in DIP 169 since the use case is no longer applicable.

[DIP 169] remove section on designated dealers

---

dips/dip-182.md

On-chain domain resolution of human readable VASP domain names into an on-chain address. Used by DIP-10 Diem ID protocol.
https://github.com/diem/dip/issues/182

On-chain Domain Resolution

---

dips/dip-183.md

Reference ID off-chain exchange DIP. Used by DIP-10 Diem ID protocol.
https://github.com/diem/dip/issues/183

Sender Initiated Reference ID Exchange

---

dips/dip-0.md

* DIP numbers are assigned by creating an GitHub issue
* Cleaned up some white space
* Discussions happen in the GitHub issue
* Abstract and Summary were extremely redundant especially when the doc
itself tends to be pretty brief if correctly written
* Noted which sections are optional more explicitly (backwards
compatibility, test cases)
* Made test case requirement more explicit
* Implementations is not an invitation to put code into DIPs but rather links to
implementations
* We should add a proper copyright notice to each dip

tweaks to dip-0
